//登陆
export const LOGINING_RESULT= 'LOGINING_RESULT';
export const LOGINED_RESULT= 'LOGINED_RESULT';
export const LOGOUT_RESULT= 'LOGOUT_RESULT';
export const GET_AUTHCODE_RESULT= 'GET_AUTHCODE_RESULT';
export const REGISTER_RESULT= 'REGISTER_RESULT';

